### ISSUE TITLE
Configuration for hardware key customisation / hardware key light enabling is missing.

### ISSUE THREAD

**Issue by luke-apk** [DotOS/android_frameworks_base#19]

**Comment by mohancm** [comment]
@ExpressLuke Ok

**Comment by luke-apk** [comment]
Is it possible to add these to framework so that they can be enabled on devices still bearing hw keys with lights (i.e Samsung Galaxy S7 edge)

- In addition the ability to toggle between using hw keys and nav bar exclusively, as hardware keys in current state has gestures enabled by default with half broken functionality.

**Comment by dofrancis** [comment]
It should be like this commit I think: https://github.com/PixelExperience/frameworks_base/commit/132cb5109cc1f3d2e5a2901ffdb5d09cdb9648d9.

**Comment by mohancm** [comment]
yes we gonna add those
