### ISSUE TITLE
Check frameworks/base/tools/aapt/Main.cpp:270

### ISSUE THREAD

**Issue by IacobIonut01** [DotOS/android_frameworks_base#2]
error: unterminated conditional directive
#ifdef AAPT_COMPRESS

**Comment by ganeshi4u** [comment]
i have pushed the [fix](https://github.com/DotOS/android_frameworks_base/commit/80f35c9d17766f8e0b0085c5f14f2c585c2f75c3). It should be fine now.
thank you.

**Comment by IacobIonut01** [comment]
always
