### ISSUE TITLE
Cannot build with "make dist"

### ISSUE THREAD

**Issue by sbwml** [DotOS/android_frameworks_base#20]
Even if `make api-stubs-docs-non-updatable-update-current-api`, still build error.

Get logs:

`@@ -12538,13 +12538,6 @@ public final class VersionedPackage impl
 
 package android.content.res {
 
-  public final class AccentUtils {
-    method public static int getDarkAccentColor(int);
-    method public static int getLightAccentColor(int);
-    method public static boolean isResourceDarkAccent(@Nullable String);
-    method public static boolean isResourceLightAccent(@Nullable String);
-  }
-
   public class AssetFileDescriptor implements java.io.Closeable android.os.Parcelable {
     ctor public AssetFileDescriptor(android.os.ParcelFileDescriptor, long, long);
     ctor public AssetFileDescriptor(android.os.ParcelFileDescriptor, long, long, android.os.Bundle);

******************************
You have tried to change the API from what has been previously approved.

To make these errors go away, you have two choices:
   1. You can add '@hide' javadoc comments (and remove @SystemApi/@TestApi/etc)
      to the new methods, etc. shown in the above diff.

   2. You can update current.txt and/or removed.txt by executing the following command:
         make api-stubs-docs-non-updatable-update-current-api

      To submit the revised current.txt to the main Android repository,
      you will need approval.
****************************** `

Current solution:
Revert: 
`https://github.com/DotOS/android_frameworks_base/commit/f537a08f123f9bb7fb64431c51ed073120df0e53`

Re-Add:
`https://github.com/DotOS/android_frameworks_base/commit/1290eb0d55125fcccde9d3a7473f21fff293bdc2`

**Comment by mohancm** [comment]
Thanks for reporting, I will check
