### ISSUE TITLE
Lockscreen before AOD

### ISSUE THREAD

**Issue by Innborne** [DotOS/android_frameworks_base#28]
Before locking phone with enabled AOD shows lockscreen

**Comment by mohancm** [comment]
Can you provide us more information on this?

**Comment by ghost** [comment]
> Can you provide us more information on this?

Yes, sure
https://drive.google.com/file/d/1--9d2OhI_WUyLk6YblRf7vWjnbKHOjrn/view?usp=drivesdk
Mi 9T

**Comment by mohancm** [comment]
this is fixed with - 35ab00bb50f4a65f8de77c8257c8e855e167c22a

**Comment by ghost** [comment]
> this is fixed with - [35ab00b](https://github.com/DotOS/android_frameworks_base/commit/35ab00bb50f4a65f8de77c8257c8e855e167c22a)

Screenrecord from 11.06 build
