### ISSUE TITLE
check frameworks/base/cmds/bootanimation/BootAnimation.cpp

### ISSUE THREAD

**Issue by IacobIonut01** [DotOS/android_frameworks_base#3]
lines 391 392 393 394 395

ERRORS : 
error: use of undeclared identifier 'IMG_ENC'
error: use of undeclared identifier 'IMG_ENC'
error: use of undeclared identifier 'IMG_OEM'
error: use of undeclared identifier 'IMG_OEM'
error: use of undeclared identifier 'IMG_SYS'
error: use of undeclared identifier 'IMG_SYS'

**Comment by ganeshi4u** [comment]
`TARGET_BOOTANIMATION_PRELOAD = true`

You need to have this flag in your device tree.

**Comment by IacobIonut01** [comment]
tried that , same error
I removed
 #ifdef PRELOAD_BOOTANIMATION
    // Preload the bootanimation zip on memory, so we don't stutter
    // when showing the animation
    FILE* fd;
    if (encryptedAnimation && access(getAnimationFileName(IMG_ENC), R_OK) == 0)
        fd = fopen(getAnimationFileName(IMG_ENC), "r");
    else if (access(getAnimationFileName(IMG_OEM), R_OK) == 0)
        fd = fopen(getAnimationFileName(IMG_OEM), "r");
    else if (access(getAnimationFileName(IMG_SYS), R_OK) == 0)
        fd = fopen(getAnimationFileName(IMG_SYS), "r");
    else
        return NO_ERROR;

    if (fd != NULL) {
        // Since including fcntl.h doesn't give us the wrapper, use the syscall.
        // 32 bits takes LO/HI offset (we don't care about endianness of 0).
#if defined(__aarch64__) || defined(__x86_64__)
        if (syscall(__NR_readahead, fd, 0, INT_MAX))
#else
        if (syscall(__NR_readahead, fd, 0, 0, INT_MAX))
#endif
            ALOGW("Unable to cache the animation");
        fclose(fd);
    }
#endif

and worked

**Comment by mohancm** [comment]
hello @DarkWoodens this rom is still wip,  we are still sorting the things now and adding features.
i recommend not to try compiling this rom!!
once everything is fine, will post on xda or other medium :)
