### ISSUE TITLE
MonetWannabe: Shades of black and gray

### ISSUE THREAD

**Issue by CodeWithShreyans** [DotOS/android_frameworks_base#34]
If shades of black or grey are chosen from the wallpaper then icons or text in the UI are barely visible or not at all

**Comment by IacobIonut01** [comment]
Please send the wallpaper and the result

**Comment by CodeWithShreyans** [comment]
![Screenshot_20210726-200630](https://user-images.githubusercontent.com/70191184/127007309-c80d1bd1-2d47-447e-ad22-524145c71c0e.png)
![Screenshot_20210726-200622](https://user-images.githubusercontent.com/70191184/127007322-103cc9b7-4261-4587-a832-508ef2d2d737.png)
![Screenshot_20210726-200430](https://user-images.githubusercontent.com/70191184/127007327-51962733-ef1c-4d9c-9d1a-e0ba23456a3e.png)
![Screenshot_20210726-200439](https://user-images.githubusercontent.com/70191184/127007331-b9641221-03f1-4fda-9c4a-04fe79009985.png)

**Comment by IacobIonut01** [comment]
Send the wallpapers themselves

**Comment by CodeWithShreyans** [comment]
![Amoledbackgrounds_njsh5t](https://user-images.githubusercontent.com/70191184/127024969-d8e431ba-429b-4069-80a6-dc5477e2a6cb.jpg)
![Amoledbackgrounds_kezbox](https://user-images.githubusercontent.com/70191184/127024979-dc6e5769-3e76-4e8a-83f8-8537d5df5475.jpg)

**Comment by IacobIonut01** [comment]
![Screenshot_20210726-193320](https://user-images.githubusercontent.com/19311643/127025701-4a84faac-e025-4f80-8c1b-e5969720ec9c.png)
![Screenshot_20210726-193323](https://user-images.githubusercontent.com/19311643/127025706-4009f212-fe07-44ba-b5d2-3aed7fb866f2.png)
![Screenshot_20210726-193424](https://user-images.githubusercontent.com/19311643/127025708-11d5e245-bc6a-4013-8f54-1c9245dfd327.png)
![Screenshot_20210726-193427](https://user-images.githubusercontent.com/19311643/127025710-3e761ec5-a63f-4602-af32-c79cd0b4d4b8.png)


Make sure you're on the latest version of dotOS - 5.1.1+

**Comment by CodeWithShreyans** [comment]
@IacobIonut01 Are you using the 128 color setting?

**Comment by CodeWithShreyans** [comment]
I am on 5.1.2-GAPPS

**Comment by DestroyerXyz** [comment]
I dragged around the number of colors generated slider and put it back on 128 and now it looks like this
# #
![Screenshot_20210726-221531](https://user-images.githubusercontent.com/70191184/127027319-302178af-8658-4d04-9d2f-94debc720f34.png)
